# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.version.outputs.tag }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_pattern: 'v*.*.*'
        release_name: 'Release ${{ github.ref }}'
  
  use-generated-tag:
    needs: generate-version
    runs-on: ubuntu-latest

    steps:
      - name: Use generated version tag
        run: echo "Generated version tag:" ${{ needs.generate-version.outputs.version_tag }}
